### ISSUE TITLE
Return already cleaned urls

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/URLCleaner-deprecated-#1]
AS A ShopRulesGenerator
I WANT TO get a clean version of an url, without any clicktracker attached
TO visit the cleaned url and download it.

Acceptance criteria:

- [x] Accepting GET-Requests on /clean with the _dirty_ url as parameter.
- [x] Returning the same url, if it doesn´t have a click tracker attached.

**Comment by deeps96** [comment]
Please use port 2118 for the URLCleaner.

**Comment by dey4ss** [comment]
-deprecated-
