### ISSUE TITLE
Return cleaned UTM urls

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/URLCleaner-deprecated-#2]
AS A ShopRulesGenerator
I WANT TO get a clean version of an url, without any clicktracker attached
TO visit the cleaned url and download it.

Acceptance criteria:
- [x] Use the existing REST-route specified in #1 
- [x] Remove UTM Parameters and return the cleaned url.

**Comment by dey4ss** [comment]
-deprecated-
