### ISSUE TITLE
Remove parameters of url if possible

### ISSUE THREAD

**Issue by deeps96** [HPI-BP2017N2/URLCleaner-deprecated-#3]
AS A ShopRulesGenerator
I WANT TO get a clean version of an url, without any clicktracker attached
TO visit the cleaned url and download it.

Acceptance criteria:
- [x] Use route specified in #1 
- [x] Remove all parameters specified in url, without removing necessary product ids.
- [ ] If product ids would get removed, the Cleaner should recognize this and add it to the blacklisted urls.

**Comment by dey4ss** [comment]
-deprecated-
